name: Template Review Request
description: Request template verification
labels: [add-template]
body:
  - type: input
    id: github_link
    attributes:
      label: '"Link to GitHub repo"'
      placeholder: https://github.com/xxx
    validations:
      required: true
  - type: input
    id: npm_link
    attributes:
      label: '"Link to NPM package"'
      placeholder: https://www.npmjs.com/package/xxx
    validations:
      required: true
  - type: dropdown
    id: category
    multiple: true
    attributes:
      label: Category
      description: What is the category of your template?
      options:
        - action (Default)
        - ui (Edge)
        - mesh (Edge)
        - event (Edge)
        - CI/CD (Edge)
    validations:
       required: true
