name: Template Review Request
description: Request template verification
labels: [add-template]
body:
  - type: input
    id: github_link
    attributes:
      label: '"Link to GitHub repo"'
      placeholder: https://github.com/xxx
    validations:
      required: true
  - type: input
    id: npm_link
    attributes:
      label: '"Link to NPM package"'
      placeholder: https://www.npmjs.com/package/xxx
    validations:
      required: true
  - type: dropdown
    id: extension-point
    attributes:
      label: '"Extension point"'
      description: The extension point your template provides
      multiple: true
      options:
        - DX SPA
        - Asset Microservices
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: '"Category"'
      description: Select the list of categories for your template
      multiple: true
      options:
        - action
        - ui
        - mesh
        - event
        - CI/CD
    validations:
      required: true
