name: Template Check

on:
  issues:
    types: [labeled]

jobs:
  check:
    if: ${{ github.event.label.name == 'review-request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Verify Template
        uses: lenaorobei/verify-template@main
  comment-success:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ always() && needs.check.outputs.result === 'pass' }}
    steps:
      - uses: ben-z/actions-comment-on-issue@1.0.2
        with:
          message: "Congratulations! Your template has been verified and added to the Template Registry.\n
                   Feel free to add *Verified by Adobe* badge to your template repo:\n
                   [![verified-by-adobe](https://badgen.net/badge/adobe/verified/green)](https://github.com/lenaorobei/template-registry-poc)\n
                   ```\n
                   [![verified-by-adobe](https://badgen.net/badge/adobe/verified/green)](https://github.com/lenaorobei/template-registry-poc)\n
                   ```\n
                   \n
                   Thank you for your contribution to the Adobe App Builder Community.\n"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
