name: Template Verification

defaults:
  run:
    shell: bash

on:
  issues:
    types: [labeled]
  issue_comment:
    types: [created]
jobs:
  parse-issue-form-body:
    name: Parse Issue Form Body
    runs-on: ubuntu-latest
    if: (github.event.label.name == 'add-template') || (github.event_name == 'issue_comment' && github.event.comment.body == '/check')
    outputs:
      github-link: ${{ steps.issue-input.outputs.github-link }}
      npm-link: ${{ steps.issue-input.outputs.npm-link }}
      npm-package: ${{ steps.issue-input.outputs.npm-package }}
    steps:
      - name: Parse Issue Form Body
        uses: peter-murray/issue-forms-body-parser@v2
        id: issue-payload
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: ${{ github.event.issue.number }}
          separator: "###"
          label_marker_start: '"'
          label_marker_end: '"'
      - name: Parse Issue Payload
        id: issue-input
        run: |
          github_link=$(echo '${{ steps.issue-payload.outputs.payload }}' | jq '."Link to GitHub repo"')
          echo "::set-output name=github-link::$github_link"
          npm_link=$(echo '${{ steps.issue-payload.outputs.payload }}' | jq '."Link to NPM package"')
          echo "::set-output name=npm-link::$npm_link"
          npm_package_path="https://www.npmjs.com/package/"
          npm_package="${npm_link/$npm_package_path/}"
          echo "::set-output name=npm-package::$npm_package"
  add-to-registry:
    name: Add to Template Registry
    runs-on: ubuntu-latest
    needs: [parse-issue-form-body]
    if: ${{ always() && (needs.parse-issue-form-body.result == 'success') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Change registry.json
        run: node add-to-registry.js '$(echo "npm view --json ${{ needs.parse-issue-form-body.outputs.npm-package }}" '
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v8
        with:
          add: registry.json
          default_author: github_actions
          message: Add template to the Registry
          push: true
  success-close-issue:
    name: Close issue
    runs-on: ubuntu-latest
    needs: [add-to-registry]
    if: ${{ always() && needs.add-to-registry.result == 'success' }}
    steps:
      - uses: peter-evans/close-issue@v1
        with:
          comment: ":white_check_mark: Congratulations! Your template has been verified."
          token: ${{ secrets.GITHUB_TOKEN }}
  fail-validation-comment:
    name: Validation failed
    runs-on: ubuntu-latest
    needs: [add-to-registry]
    if: ${{ always() && (needs.add-to-registry.result != 'success') }}
    steps:
      - uses: ben-z/actions-comment-on-issue@1.0.2
        with:
          message: |
            The following checks failed:
            Comment `/check` to run checks again.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
