name: Template Check

on:
  issues:
    types: [labeled]

jobs:
  check:
    if: ${{ github.event.label.name == 'review-request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Verify Template
        uses: lenaorobei/verify-template@main
  add-to-registry:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ always() && contains(join(needs.check.result, ','), 'success') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Change registry.json
        run: node add-to-registry.js "${{ github.event.issue.body }}"
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v8
        with:
          add: registry.json
          default_author: github_actions
          message: Add template to the registry
          push: true
  success-comment:
    runs-on: ubuntu-latest
    needs: [add-to-registry]
    if: ${{ always() && contains(join(needs.add-to-registry.result, ','), 'success') }}
    steps:
      - uses: ben-z/actions-comment-on-issue@1.0.2
        with:
          message: ":white_check_mark: Congratulations! Your template has been verified and added to the Template Registry."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  fail-validation-comment:
    runs-on: ubuntu-latest
    needs: [check]
    if: ${{ always() && contains(join(needs.check.result, ','), 'failure') }}
    steps:
      - uses: badsyntax/github-action-issue-comment@master
        name: Adding validation errors
        with:
          action: 'create'
          template: '.github/fail-validation-comment-template.hbs'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          template-inputs: |
            {
              "errors": ${{ needs.check.outputs.errors }}
            }
