name: Template Check

on:
  issues:
    types: [opened]

jobs:
  verify:
    if: ${{ github.event.label.name == 'review-request' }}
    name: Verify template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Verify template
        uses: magento-eqp/verify-template@main
  add-to-registry:
    name: Add to the Registry
    runs-on: ubuntu-latest
    needs: verify
    if: ${{ always() && contains(join(needs.verify.result, ','), 'success') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Change registry.json
        run: node add-to-registry.js "${{ github.event.issue.body }}"
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v8
        with:
          add: registry.json
          default_author: github_actions
          message: Add template to the Registry
          push: true
  success-close-issue:
    name: Close issue
    runs-on: ubuntu-latest
    needs: [add-to-registry]
    if: ${{ always() && contains(join(needs.add-to-registry.result, ','), 'success') }}
    steps:
      - uses: peter-evans/close-issue@v1
        with:
          comment: ":white_check_mark: Congratulations! Your template has been verified and added to the Template Registry."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  fail-verification-comment:
    name: Verification failed notification
    runs-on: ubuntu-latest
    needs: [verify]
    if: ${{ always() && contains(join(needs.verify.result, ','), 'failure') }}
    steps:
      - uses: ben-z/actions-comment-on-issue@1.0.2
        with:
          message: ":x: Template validation failed."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
