name: Validate registry.json

on:
  push:
    paths:
      - 'registry.json'
jobs:
  validate-json:
    name: Validate registry.json
    runs-on: ubuntu-latest
    steps:
      - name: Commit and push changes
        uses: vanekj/validate-json-action@v1
        with:
          schema: registry.schema.json
          pattern: registry.json
  create-bug:
    name: Create GitHub issue
    runs-on: ubuntu-latest
    needs: [ validate-json ]
    if: ${{ always() && (needs.validate-json.result != 'success') }}
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/invalid-registry-json.md
